[package]
name = "helium"
version = "0.1.0"
authors = ["Martin Hanz√≠k <martin@hanzik.com>", "Kuba Marek <bluecube@seznam.cz>"]

[dependencies]
glium = "0.16.0"
glium_text = "0.11.0"
cgmath = "0.12"
clap = "2.19.2"
clippy = {version = "*", optional = true}
